name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v2
  #     - name: Run tests
  #       run: ./gradlew test
  #     - name: Upload html test report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: index.html
  #         path: app/build/reports/tests/testDebugUnitTest/index.html
  #     - name: Upload test report directory
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: reports
  #         path: app/build/reports/tests/testDebugUnitTest/
  # instrumentation-test:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v2
  #     - name: Run espresso tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 29
  #         script: ./gradlew connectedCheck --stacktrace
  static-code-analysis:
    # needs: [unit-test, instrumentation-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    needs: [static-code-analysis]
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with: 
          name: falleria-alpha-app.apk
          path: app/build/outputs/apk/debug/app-debug.apk
  distribute-for-alpha-testing:
    needs: [build]
    name: Distribut for Alpha testing
    runs-on: ubuntu-latest
    steps:
      - name: Download latest artifact
        uses: actions/download-artifact@v2
        with:
          name: falleria-alpha-app.apk
      - name: Upload to app center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ajit-dev/Falleria-Android
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: FalleriaAlphaTesters
          file: app-debug.apk
          notifyTesters: true
          debug: true
